export default {
  hit: "Hit",
  stand: "Stand",
  deal: "Deal",
  double: "Double",
  settings: "Settings",

  hitTitle: "Draw a card",
  standTitle: "End your turn",
  dealTitle: "Start a new round",
  bustedTitle: "Busted (over 21)",
  roundOverTitle: "Round is over",
  dealDisabledTitle: "Finish the round first",
  doubleTitle: "Double down (not implemented)",
  doubleDisabledTitle: "Double is only available on the first two cards",
  bankrollLabel: "Bankroll",
  betLabel: "Bet",
  scoreLabel: "Score",
  playerLabel: "Player",
  dealerLabel: "Dealer",
  youBustedDealerWins: "You busted. Dealer wins.",
  dealerBustedYouWin: "Dealer busted. You win!",
  youWin: "You win!",
  dealerWins: "Dealer wins.",
  pushTie: "Push (tie).",
  outOfChips: "Out of chips!",
  notEnoughToDouble: "Not enough chips to double.",
  doubleHint: "Double = bet x2, draw 1 card, then stand.",
};