export default {
  hit: "要牌",
  stand: "停牌",
  deal: "发牌",
  double: "加倍",
  settings: "设置",

  hitTitle: "抽一张牌",
  standTitle: "结束本回合",
  dealTitle: "开始新一局",
  bustedTitle: "爆牌（超过21点）",
  roundOverTitle: "本局已结束",
  dealDisabledTitle: "请先结束当前回合",
  doubleTitle: "加倍（暂未实现）",
  doubleDisabledTitle: "加倍只能在前两张牌时使用",
  bankrollLabel: "筹码",
  betLabel: "下注",
  scoreLabel: "点数",
  playerLabel: "玩家",
  dealerLabel: "庄家",
  doubleHint: "加倍 = 下注翻倍 + 只再抽 1 张牌 + 然后自动停牌。",
  youBustedDealerWins: "你爆牌了，庄家赢。",
  dealerBustedYouWin: "庄家爆牌，你赢了！",
  youWin: "你赢了！",
  dealerWins: "庄家赢。",
  pushTie: "平局（Push）。",
  outOfChips: "筹码不够了！",
  notEnoughToDouble: "筹码不足，无法加倍。",
  doubleHint: "加倍 = 下注翻倍 + 只抽1张 + 自动停牌。",
};